development:

  rss:
    "www.collegiatetimes.com": "Collegiate Times"
    "blogs.roanoke.com": "The Burgs Blog"
    "www.roanoke.com": "The Roanoke Times"
    "www.vtnews.vt.edu": "Virginia Tech News"
    "www.bev.net": "Blacksburg Electronic Village"
    "citizensfirstnrv.org": "Citizens First"
    "www.christiansburg.org": "Christiansburg Virginia"
    "downtownblacksburg.wordpress.com": "Downtown Blacksburg Blog"
    "www.myvaresources.com": "Depotdazed"
    "nrvnews.com": "NRV News"
    "www2.swvatoday.com": "SWVA Today"
    "www.southwesttimes.com": "The Southwest Times"
    "www.lwvmcva.org": "League of Women Voters in Montgomery County"
    "www.blacksburg.va.us": "Town of Blacksburg"
    "swvanews.com": "Southwest Virginia Blogs"
    "www.progressandmain.com": "Progress and Main"
    "www.montva.com": "Montgomery County VA"
    "www.blueridgemuse.com": "Blue Ridge Muse"
    "blacksburgdailyphoto.blogspot.com": "Blacksburg Daily Photo"
    "blacksburgmayor.wordpress.com": "Blacksburg Mayor's Blog"
    "newrivervoice": "New River Voice"
    "ourvalley.org": "Our Valley"
    "blog.pcva.us": "Pulaski County"
    "eastmontva.wordpress.com": "EastMont VA"
